### ISSUE TITLE
AppCompatActivity

### ISSUE THREAD

**Issue by sargunster** [Karumi/Rosie#46]
`RosieActivity` should extend from `AppCompatActivity` (or make a new `RosieAppCompatActivity`) to allow using things like `setSupportActionBar()`

I think there is no downside to changing `RosieActivity` to extend `AppCompatActivity` since both extend `FragmentActivity` and Rosie already depends on the support library.

**Comment by flipper83** [comment]
Hi @sargunster ,

Have sense a RosieAppCompactActivity that it is equals to RosieActivity extending from AppCompactActivity.

Feel free to send a PullRequest with the new activity. 

Thank you.

**Comment by sargunster** [comment]
Will send a PR soon.
