### ISSUE TITLE
Feedback from DroidsOnRoids

### ISSUE THREAD

**Issue by pedrovgs** [Karumi/Rosie#48]
@flipper83 @Serchinastico we have some feedback about Rosie in this blog post: http://www.thedroidsonroids.com/blog/android/rosie-lets-dive-into-clean-architecture/ There are some things we could improve like: change some methods visibility in the RosiePresenter to improve the class testability from the unit test point of view. What do you think?

**Comment by Serchinastico** [comment]
Yup, the author makes a solid point about testing. The visibility of some of the classes she mentions are there for a reason though. 
Maybe it's just a crazy idea but what about creating an artifact for testing purposes that expose those methods?

**Comment by pedrovgs** [comment]
Maybe @pszklarska can give us more detailed feedback. We can not comment in the blog post and I don't find the DroidsOnRoids twitter :)

**Comment by pszklarska** [comment]
Hi guys, nice to see your response for my article ;) As I wrote, there were some issues that bothered me while testing. I mentioned them in article, but if you need more info, I'll be glad to help.

@pedrovgs why can't you comment in the blog post?

**Comment by pedrovgs** [comment]
hahaha I didn't see the comments section at the end of the "other posts" links. Sorry :)

**Comment by pedrovgs** [comment]
@pszklarska one of your suggestions is already in review #47

**Comment by pszklarska** [comment]
Great, so I wait for update :)
