### ISSUE TITLE
RosieSupportFragment

### ISSUE THREAD

**Issue by sargunster** [Karumi/Rosie#60]
I think there should be a RosieSupportFragment like the RosieFragment, because support fragments are needed for things like the TabLayout in the material design library. This is a similar issue to #46.

**Comment by sargunster** [comment]
I've submitted PR #61 to fix this.

**Comment by Serchinastico** [comment]
We will review it ASAP, thanks for your PR!

**Comment by pedrovgs** [comment]
Thanks @sargunster !
