### ISSUE TITLE
I have another question, How can I include third library in my arr like your rosie?

### ISSUE THREAD

**Issue by h3clikejava** [Karumi/Rosie#71]
I have many third library in my android library like Rosie with dagger and Butter Knife.But my arr package not include this, so It can't reference this library.

How can i build it let my arr include this third library?Thx

**Comment by flipper83** [comment]
I'm trying to understand you problem. are you trying to include Rosie in our your own library and your library do not compile?

Can you give us any kind of trace or error log about this one? are you using gradle? can you copy us how do you include it?

**Comment by h3clikejava** [comment]
Sorry, My English is very bad.
I want write a publish library, Its function like Rosie. At last I made a arr file to upload on Bintray, and use it.

But other project use my library will lost third library.Do you know i mean?
My library use butterknife、threetenabp、RxJava...etc. But last arr not include these.

I see Rosie use one line with 'compile com.karumi.rosie:rosie:2.0.0' can include dagger and butterknife...
How can i do it let my library can use only one line compile include it used third librarys?

Think you very very much! Best wishes for you

**Comment by pedrovgs** [comment]
@h3clikejava If I understand you, your problem is not related to Rosie. Am I wrong? Your problem is related with third party libraries like Butterknife. Remember that the latest version of Butterknife can not be used into an aar.

**Comment by flipper83** [comment]
Hi,

If want to export dependencies in you aar review:
1) That you are including in you build.xml as compile and not provided. Use provided only for that libs that you want to ignore it.
2) That your pom is well formed, if you review our build.xml we use the chrisbanes plugin for export the library and generate the pom.
3) check that you don't have any bug invoking the lib in your sample, sometimes android said that you have a include error and not find the library, review you sample code too.

**Comment by h3clikejava** [comment]
Yes, @pedrovgs is right. my problem is not related to Rosie, My problem is related with third party libraries like threetenabp etc... 

flipper83 I seem to understand what you mean, I'm studying it carefully. 
Thank you for your help. Thank you so much.
