### ISSUE TITLE
Searching in repositories

### ISSUE THREAD

**Issue by lujop** [Karumi/Rosie#81]
How do you implement searches in repositories (eg paginated results where user can filter by a text expression)?

Is the intended usage  to use a repository factory that creates a repository for search result?
If this is the intended usage how do you implement caching? Did you use some type of repository caching, **manually** create appropriate caching datasources?
Or simple recreate all and try to move caching to upper levels like http request/response caching.

I think that this is a pretty common repository use case and will be nice to have some support in the framework and example usage in the sample.

**Comment by pedrovgs** [comment]
Hi @lujop!

You can use the current repositories implementation adding a key to search containing the page and the search param you need and the repository will automatically catch all your results using the TTL you've configured.

Is this the answer to your question?

**Comment by lujop** [comment]
Yes thanks,
