### ISSUE TITLE
provide a proguard rules

### ISSUE THREAD

**Issue by loki666** [Karumi/Rosie#83]

**Comment by jcdom** [comment]
I'm using:

**Comment by jcdom** [comment]
I'm using:

# Dagger ProGuard rules.
# https://github.com/square/dagger

-dontwarn dagger.internal.codegen.**
-keepclassmembers,allowobfuscation class * {
    @javax.inject.* *;
    @dagger.* *;
    <init>();
}

-keep class dagger.* { *; }
-keep class javax.inject.* { *; }
-keep class * extends dagger.internal.Binding
-keep class * extends dagger.internal.ModuleAdapter
-keep class * extends dagger.internal.Stati

# Rosie framework
-keepclassmembers,allowobfuscation class * {
    @com.karumi.rosie.** *;
}
