### ISSUE TITLE
Error when running a signed APK

### ISSUE THREAD

**Issue by pinicius** [Karumi/Rosie#92]
Hi,
I do not understand what is happening.
* When I install the app from Android Studio with the debugkeystore by default, there is no problem.
* When I sign the app with the Android Studio tool and my keystore, then I pass it to the phone, install the app, execute and ERROR: This object does not contain any use case to execute. Did you forget to add the @UseCase annotation?

Why these two different behaviors with the same code?

Has something similar happened to you?

Thanks in advance

**Comment by pedrovgs** [comment]
Hi @pinicius! This is the first time we face this issue and I'm pretty sure it is related to the obfuscation configuration. When you say "When I install the app from..." are you talking about this repository code or your own app?

**Comment by pinicius** [comment]
Hi @pedrovgs!
I want mean, from my own app

**Comment by pedrovgs** [comment]
@pinicius could you check in your project if your release build obfuscates the app. If I remember properly, Rosie does not support obfuscation.

**Comment by pinicius** [comment]
In both is disabled

**Comment by pedrovgs** [comment]
If this is your build tyes configuration:

```
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
You are adding the default ``proguard-android.txt`` and also the ``proguard-rules`` configuration file  to your proguard execution. So the obfuscation could be enabled. Could you double check it?

**Comment by pedrovgs** [comment]
If you could also paste the stack trace you've found that'd be great 😃

**Comment by pinicius** [comment]
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:checkReleaseManifest UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:prepareLintJar UP-TO-DATE
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:createReleaseCompatibleScreenManifests UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:splitsDiscoveryTaskRelease UP-TO-DATE
:app:processReleaseResources UP-TO-DATE
:app:generateReleaseSources UP-TO-DATE
:app:javaPreCompileRelease UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk NO-SOURCE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
:app:mergeReleaseShaders UP-TO-DATE
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:transformClassesWithPreDexForRelease UP-TO-DATE
:app:transformDexWithDexForRelease UP-TO-DATE
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:app:transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
:app:processReleaseJavaRes NO-SOURCE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:validateSigningRelease
:app:packageRelease UP-TO-DATE
:app:assembleRelease

BUILD SUCCESSFUL in 2s
26 actionable tasks: 2 executed, 24 up-to-date

But I don't know how to avoid it :(

**Comment by pedrovgs** [comment]
[Here](https://stackoverflow.com/questions/9651703/using-proguard-with-android-without-obfuscation) you can find information about how to avoid obfuscation during your build. Could you update your app and let me know if this is the issue you are facing?

**Comment by pinicius** [comment]
Unfortunately it does not work. I've tried with the signed debug version too and the error is the same, does it make sense?

**Comment by pedrovgs** [comment]
But you said: 

> When I install the app from Android Studio with the debugkeystore by default, there is no problem.

I think the easiest way to figure out what's going on is to create an android project from scratch, upload it to a public repository and try to reproduce the bug. Could you do this so we can find the issue and fix it?

**Comment by pinicius** [comment]
I meant to sign the release of debug with my private keystore (releasekeystore)

After feeding, I will try :D

Thanks so much for your time

**Comment by pinicius** [comment]
Hi again @pedrovgs,
I have solved the problem, the use case method was not public :$
But now, the app gives me an error when I run the signed APK

```
java.lang.Error
                                                                                    at com.karumi.rosie.domain.usecase.error.ErrorFactory.createInternalException(ErrorFactory.java:42)
                                                                                    at com.karumi.rosie.domain.usecase.error.ErrorHandler.createError(ErrorHandler.java:91)
                                                                                    at com.karumi.rosie.domain.usecase.error.ErrorHandler.notifyException(ErrorHandler.java:64)
                                                                                    at com.karumi.rosie.domain.usecase.UseCaseWrapper.notifyException(UseCaseWrapper.java:47)
                                                                                    at com.karumi.rosie.domain.usecase.UseCaseWrapper.execute(UseCaseWrapper.java:41)
                                                                                    at com.karumi.rosie.domain.usecase.jobqueue.UseCaseWrapperJob.onRun(UseCaseWrapperJob.java:41)
                                                                                    at com.path.android.jobqueue.Job.safeRun(Job.java:189)
                                                                                    at com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:91)
                                                                                    at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306)
                                                                                    at java.lang.Thread.run(Thread.java:764)
```
This error not appears when I run from my repository

Any idea?

**Comment by pedrovgs** [comment]
Happy to see you've found the original issue. In order to fix this you should debug the code execution and review what's the exception thrown. The code you can see in the stack trace is only executed if someone throws an exception, so at some point your code has to be throwing an exception you are not handling. Do you still face this issue just with the signed/release version of your app? Did you disable the obfuscation as I suggested in a previous comment? Disabling obfuscation will help us to identify where the bug is.

**Comment by pinicius** [comment]
Hi @pedrovgs !
Unfortunately I'm still with the problem.
I have verified that if the minified property is false, it does not perform code reduction.
The use cases, including the components they are using, do not throw any type of exception. In fact, the information is in the database. I have a doubt, if minified is deactivated, can obfuscation occurs? Because as I have looked in the documentation there should be a folder in the path <app> / build / outputs / mapping / release / and it does not create them.

But the problem continues, if I generate the apk signed with my keystore, any type of build (debug or release), the application fails. If I sign with debugkeystore, no problem. And in both cases the information is in database without any error.

Right now I do not know where to look :(

**Comment by pedrovgs** [comment]
@pinicius minification is not equivalent to obfuscation, so if you don't minify the app you can still be obfuscating it as I commented [here](https://github.com/Karumi/Rosie/issues/92#issuecomment-367665294). If you are not able to disable the obfuscation and we can't find a way to reproduce this error..there is only one way to fix this. Create a repository on GitHub where you reproduce the error and share it with us so we can debug it manually and see what's going on.

**Comment by pinicius** [comment]
@pedrovgs One last question

I have added the code they discuss in the possible solution (link that you made me reference)

Even without using Proguard, the behavior is the same.

```
release {
            debuggable true
            minifyEnabled false
            useProguard false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
```
I do not understand what is going on, why does not it always fail?
I will continue trying to solve it. Thank you very much for your time and if you have any ideas, it will be welcome ;))

**Comment by pedrovgs** [comment]
You are welcome @pinicius I'm closing this issue for now until we have a clear scenario to reproduce the error in our hands. Feel free to create the repository I mentioned so I can personally debug what's going on.
